Edit .html .css and README file
Tshepo45/Mobile-First pull request #3
Opened 2022-08-30 11:51 UTC by Tshepo45

create a form
configure linters

2022-08-30 13:51 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Tshepo45, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors. ✔️
 - Correct use of GitHub flow. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-30 13:51 UTC, leonardodiasb commented on index.html
> +   <form action="https://formspree.io/f/mzbowdel" class="form" id="form">
- [ ] Your form post is not working because it does not have a method attached to it. Kindly add a POST method in order for to it work. Please read the [Formspree service](https://formspree.io/html) instructions.
 - [ ] The style of your form does not closely resemble the template you are following. The fonts you used are not the same, the background image that is present in the template is missing, the form is not centered on the page, there is whitespace on both sides of the form, the form button is not left aligned and the style does not follow the template, etc. Kindly correct the differences and please make sure you stick to the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) design as much as possible.
 -Your design:
<img width="478" alt="image" src="https://user-images.githubusercontent.com/61919617/187454712-84eb9d92-d402-40eb-bf72-a8ad7a52fad4.png">
-Figma design:
<img width="310" alt="image" src="https://user-images.githubusercontent.com/61919617/187454780-5eaeb76b-6815-4bd1-aec4-34355d1d5a7e.png">

2022-08-30 21:11 UTC, ichala requested changes
Hi @Tshepo45 , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Form now works ✅
-  No linter errors ✅

 ## Required Changes ♻️

- [ ] **_Check the comments below_**

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-30 21:11 UTC, ichala commented on styles.css
> +  border-radius: 8px;
- [ ] kindly fix your design,its still doesn't look like Figma's design try to follow the button styles fonts and margins ... 
- [ ] kindly fix the overflow as well to prevent users from scrolling right and left

![formm](https://user-images.githubusercontent.com/89282221/187543727-b2b0561a-add6-4edc-9408-53e19f9b2c96.gif)

2022-08-31 16:12 UTC, aimemalaika requested changes
Hi @Tshepo45 , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## Suggested changes

- [ ] As requested by the reviewer kindly fix the overflow and make sure that background of your form fit the entire page
<img width="420" alt="Screen Shot 2022-08-31 at 18 11 45" src="https://user-images.githubusercontent.com/28307960/187727131-aa9cc5b1-8d08-4ce8-bbc0-ccdc3971b99c.png">


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-31 22:56 UTC, ShahierNashaat approved these changes
Hi @Tshepo45, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 

- Correct use of GitFlow ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️
- Your readme looks professional ✔️
- Your code is clean and well documented ✔️

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-01 07:51 UTC, Tshepo45 reviewed
Good work done please make changes that I have requested.👌

2022-09-01 07:51 UTC, Tshepo45 commented on index.html
> -        <li> <a href="https://twitter.com/@tshepomakama45"> <img src="Img/Twitter.png" alt="twiter"/></a> </li>
Good work so far but please stick to the html format structure

2022-09-01 08:38 UTC, merged